### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by 4711KingOfHearts** [4711KingOfHearts/ProjectCynthia-node#1]
- [X] Allow for logins to Showdown
- [X] Create a new random battle
- [ ] Cynthia move engine - random (choose a valid move at random)
- [ ] Cynthia move engine - minmax (choose the move most likely to have the biggest delta in unfainted Pokemon/damage across both teams)
- [ ] Cynthia move engine - Nash Equilibrium (calculate the Nash Equilibrium and choose a move from its distribution
- [ ] Cynthia move engine - Cynthia (Cynthia teaches herself the best strategy and chooses a move based on that)
- [ ] Create a new team-based battle
- [ ] Create Express frontend to view and control Cynthia
